name: Android Dev Signed Release

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build-dev-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission to gradlew
        run: chmod +x android/gradlew

      - name: Build Signed Release APK
        env:
          KEYSTORE_PATH: android/app/release-key.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: release-key-alias
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: dev-signed-release-apk
          path: app/build/outputs/apk/release/*.apk
